version: '3.8'

services:
  monez_automation-playwright:
    build:
      context: .
      dockerfile: Dockerfile
    image: monez_automation_playwright 
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - NODE_ENV=production
    command: npx playwright test
    ports:
      - "3000:3000"
    container_name: monez_automation_playwright
    restart: unless-stopped
